##ridge

```{r}
install.packages("mltools")
library(mltools)
library(data.table)
```

data
```{r}
dt1 = read.csv("cv_1.csv")
dt2 = read.csv("cv_2.csv")
dt3 = read.csv("cv_3.csv")
dt4 = read.csv("cv_4.csv")
dt5 = read.csv("cv_5.csv")
test = read.csv("test_set.csv")

dt = rbind(dt1,dt2,dt3,dt4,dt5,test)
grade = data.frame(dt$age,dt$absences,dt$G1,dt$G2,dt$G3)
dt = dt[,c(-3,-9,-10,-30,-31,-32,-33)]


test = dt
onehot = one_hot(as.data.table(test))
onehot_remain = onehot[,c(11,12,20,21,22,39,40,41,42,43,44)]
onehot = onehot[,-c(11,12,20,21,22,39,40,41,42,43,44)]
names = names(onehot_remain)
onehot_remain = as.matrix(onehot_remain)

remain_dummy = data.frame(new = rep(0,nrow(onehot_remain)))

for(i in 1:11){
 r = range(onehot_remain[,i])[1]:range(onehot_remain[,i])[2]
 for(j in 1:length(r)){
  new = rep(0,nrow(onehot_remain))
  new[which(onehot_remain[,i] == r[j])] = 1
  new_dt = data.frame(new)
  names(new_dt) = paste(names[i],r[j])
  remain_dummy = cbind(remain_dummy,new_dt)
 }
}

clean_data = cbind(onehot,remain_dummy[,-1],grade)
write.csv(clean_data[1:63],"cv.1.csv")
write.csv(clean_data[64:126],"cv.2.csv")
write.csv(clean_data[127:189],"cv.3.csv")
write.csv(clean_data[190:252],"cv.4.csv")
write.csv(clean_data[253:316],"cv.5.csv")
write.csv(clean_data[317:395],"test.csv")
```

cross validation
```{r}
cv.1 = read.csv("cv.1.csv")[,-1]
cv.2 = read.csv("cv.2.csv")[,-1]
cv.3 = read.csv("cv.3.csv")[,-1]
cv.4 = read.csv("cv.4.csv")[,-1]
cv.5 = read.csv("cv.5.csv")[,-1]

lambda =c(1000,100,10, 1, 0.1, 0.01, 0.001)

#calculate coefficient
cal_coef = function(X,lambda,y){
  ##closed form solution
  ##set the graident = 0
  X = X
  n_lambda = lambda
  part.a = (t(X)%*%X + n_lambda*diag(90))
  inv.a = solve(part.a)
  coefficient = inv.a %*% t(X) %*% y
  return(coefficient)
}

## use coefficients to estimate test sets
## estimate error
cal_mse = function(test.set,coef){
  dt = test.set
  y = dt[,ncol(dt)]
  X = as.matrix(cbind(rep(1,nrow(dt)),dt[,-ncol(dt)]))
  est_y = X %*% coef
  mse = sum((y-est_y)^2)/nrow(dt)
  return(mse)
}

cal_rsquare = function(test.set,coef){
  dt = test.set
  y = dt[,ncol(dt)]
  y_bar = mean(y)
  X = as.matrix(cbind(rep(1,nrow(dt)),dt[,-ncol(dt)]))
  est_y = X %*% coef
  tot = sum((y-y_bar)^2)
  res = sum((y-est_y)^2)
  rsquare = 1-res/tot
  return(rsquare)
}
```

```{r}

cv_func = function(tr1,tr2,tr3,tr4,test,lambda){
  train.dt = rbind(tr1,tr2,tr3,tr4)
  test.dt = test
  
  y = train.dt[,90] #g3 grade
  X = as.matrix(cbind(rep(1, nrow(train.dt)),train.dt[,-90]))

  coef = cal_coef(X,lambda,y)
  mse = cal_mse(test.dt,coef)
  rsquare = cal_rsquare(test.dt,coef)
  
  return(list(coef = coef, MSE = mse, Rsquare = rsquare))
}

record_mse = matrix(0,6,length(lambda))#record
record_rs =  matrix(0,6,length(lambda))
for(i in 1:length(lambda)){
  ##each calculated mse
  m1 = cv_func(cv.1,cv.2,cv.3,cv.4,cv.5,lambda[i])
  m2 = cv_func(cv.1,cv.2,cv.3,cv.5,cv.4,lambda[i])
  m3 = cv_func(cv.1,cv.2,cv.5,cv.4,cv.3,lambda[i])
  m4 = cv_func(cv.1,cv.5,cv.3,cv.4,cv.2,lambda[i])
  m5 = cv_func(cv.5,cv.2,cv.3,cv.4,cv.1,lambda[i])
  ##do above procedure 5 times and get average error
  record_mse[,i] = c(m1$MSE,m2$MSE,m3$MSE,m4$MSE,m5$MSE,mean(c(m1$MSE,m2$MSE,m3$MSE,m4$MSE,m5$MSE)))
  record_rs[,i] = c(m1$Rsquare,m2$Rsquare,m3$Rsquare,m4$Rsquare,m5$Rsquare, mean(c(m1$Rsquare,m2$Rsquare,m3$Rsquare,m4$Rsquare,m5$Rsquare)))
}

colnames(record_mse) = c(lambda)
rownames(record_mse) = c(1:5,"average")
colnames(record_rs) = c(lambda)
rownames(record_rs) = c(1:5,"average")

record_mse
record_rs

```

perform in the test.set, choose lambda = 100
```{r}
test = read.csv("test.csv")[,-1]
train = rbind(cv.1,cv.2,cv.3,cv.4,cv.5)
train.y  = train[,90] #dependent var
train.x  = as.matrix(cbind(rep(1, nrow(train)),train[,-90])) #indep var
test.coef = cal_coef(train.x,100,train.y)

test.mse = cal_mse(test,test.coef)
test.sq = cal_rsquare(test,test.coef)
final = c(test.mse,test.sq)
names(final) = c("MSE","R-square")
final
```